export const courses = [
  { id: 0, name: "Calculo de una variable", row: 0, col: 0, type: "basic" },
  {
    id: 1,
    name: "Fisica Mecanica",
    row: 0,
    col: 1,
    type: "basic",
  },
  {
    id: 2,
    name: "Analisis y Resolucion de Problemas",
    row: 0,
    col: 2,
    type: "general",
  },
  {
    id: 3,
    name: "Fundamentos de Programacion",
    row: 0,
    col: 3,
    type: "general",
  },
  {
    id: 4,
    name: "complementarias de arte, deportes e idiomas",
    row: 0,
    col: 4,
    type: "complementadi",
  },
  { id: 5, name: "Ingles I", row: 0, col: 5, type: "general" },
  {
    id: 6,
    name: "Algebra lineal",
    row: 1,
    col: 0,
    type: "basic",
  },
  {
    id: 7,
    name: "Calculo Vectorial",
    row: 1,
    col: 1,
    type: "basic",
  },
  {
    id: 8,
    name: "computacion y sociedad",
    row: 1,
    col: 2,
    type: "profform",
  },
  {
    id: 9,
    name: "Programación Orientada a Objetos",
    row: 1,
    col: 3,
    type: "profform",
  },
  {
    id: 10,
    name: "comunicacion",
    row: 1,
    col: 4,
    type: "general",
  },
  { id: 11, name: "ingles II", row: 1, col: 5, type: "general" },
  {
    id: 12,
    name: "fundamentos de electricidad y sistemas digitales",
    row: 2,
    col: 0,
    type: "general",
  },
  { id: 13, name: "matematicas discretas", row: 2, col: 1, type: "basic" },
  { id: 14, name: "estructura de datos", row: 2, col: 2, type: "profform" },
  { id: 15, name: "diseno de software", row: 2, col: 3, type: "profform" },
  {
    id: 16,
    name: "sistema de bases de datos",
    row: 2,
    col: 4,
    type: "profform",
  },
  { id: 17, name: "ingles III", row: 2, col: 5, type: "general" },
  {
    id: 18,
    name: "organizacion de computadores",
    row: 3,
    col: 0,
    type: "profform",
  },
  {
    id: 19,
    name: "programacion de sistemas",
    row: 3,
    col: 1,
    type: "profform",
  },
  { id: 20, name: "estadistica", row: 3, col: 2, type: "basic" },
  {
    id: 21,
    name: "interaccion humano computador",
    row: 3,
    col: 3,
    type: "profform",
  },
  { id: 22, name: "redes de datos", row: 3, col: 4, type: "profform" },
  { id: 23, name: "ingles IV", row: 3, col: 5, type: "general" },

  { id: 24, name: "sistemas operativos", row: 4, col: 0, type: "profform" },
  { id: 25, name: "analisis de algoritmos", row: 4, col: 1, type: "profform" },
  {
    id: 26,
    name: "desarrollo de aplicaciones web y moviles",
    row: 4,
    col: 2,
    type: "profform",
  },
  {
    id: 27,
    name: "ingenieria de software I",
    row: 4,
    col: 3,
    type: "profform",
  },
  {
    id: 28,
    name: "emprendimiento e innovacion",
    row: 4,
    col: 4,
    type: "general",
  },
  { id: 29, name: "ingles V", row: 4, col: 5, type: "general" },
  {
    id: 30,
    name: "seguridad de la informacion",
    row: 5,
    col: 0,
    type: "profform",
  },
  {
    id: 31,
    name: "metodologia de la investigacion en computacion",
    row: 5,
    col: 1,
    type: "profform",
  },
  {
    id: 32,
    name: "lenguajes de programacion",
    row: 5,
    col: 2,
    type: "profform",
  },
  {
    id: 33,
    name: "ingenieria de software II",
    row: 5,
    col: 3,
    type: "profform",
  },
  {
    id: 34,
    name: "ciencias de la sostenibilidad",
    row: 5,
    col: 4,
    type: "basic",
  },
  {
    id: 35,
    name: "practicas de servicio comunitario",
    row: 5,
    col: 5,
    type: "cominternships",
  },
  {
    id: 36,
    name: "inteligencia artificial",
    row: 6,
    col: 1,
    type: "profform",
  },
  {
    id: 37,
    name: "sistemas de informacion",
    row: 6,
    col: 2,
    type: "profform",
  },
  {
    id: 38,
    name: "sistemas distribuidos y computacion en la nube",
    row: 6,
    col: 3,
    type: "profform",
  },
  {
    id: 39,
    name: "direccion de proyectos informaticos",
    row: 6,
    col: 4,
    type: "profform",
  },
  {
    id: 40,
    name: "itinerario",
    row: 6,
    col: 5,
    type: "itinerary",
  },
  {
    id: 41,
    name: "complementarias de humanisticas",
    row: 7,
    col: 2,
    type: "complementh",
  },
  {
    id: 42,
    name: "materia integradora de computacion",
    row: 7,
    col: 3,
    type: "curricularintegrationunit",
  },
  {
    id: 43,
    name: "itinerario",
    row: 7,
    col: 5,
    type: "itinerary",
  },
  {
    id: 44,
    name: "practicas preprofesionales empresariales",
    row: 8,
    col: 5,
    type: "profinternships",
  },
];
